version: '3.8'
services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - db_data:/data/db
    networks:
      - backend

  backend:
    build: backend/
    container_name: backend_app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_password@mongodb:27017/
    ports:
      - "8000:8000" 
    networks:
      - backend

  frontend:
    build: frontend/
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "3001:3001" 
      - "3000:3000" 
    networks:
      - backend

networks:
 backend:
  driver: bridge

volumes:
 db_data:
