version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - mongodb_data:/data/db

#   myapp:
#     build: db/
#     container_name: db_test
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_URI=mongodb://mongo_user:mongo_password@mongodb:27017/
#     ports:
#       - "8080:8080"  # Change if your app uses a different port

volumes:
  mongodb_data: