version: '3.8'
services:
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - db_data:/data/db
    networks:
      - backend

  backend:
    build: db/
    container_name: backend_app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_password@mongodb:27017/
    ports:
      - "8080:8080"  # Change if your app uses a different port
    networks:
      - backend

networks:
 backend:
  driver: bridge

volumes:
 db_data:
